# Generated by Django 3.2.4 on 2021-07-11 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialauth', '0002_auto_20210711_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactuser',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 7, 11, 19, 26, 13, 205014)),
        ),
    ]
