# Generated by Django 3.2.4 on 2021-07-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialauth', '0003_contactuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuser',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
